version: "3.8"
services:
  courseregistrationsystemdockercontainer:
    build:
      context: "."
      dockerfile: "Dockerfile"
    restart: always
    ports:
      - "8080:8080"
  course_registration_system-db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASS}
    env_file:
    - .env